### PR TITLE
Update Audio Question Warning

### PR DESCRIPTION
**Pull request by nick-benoit14**
There is a story to only display max time limit warning, when the number that has been entered is over that limit. This makes that change.

### CODE REVIEW

**Comment by BenHSmith13** [comment]
Why are there a bunch of deserialization commits in this PR?

**Comment by nick-benoit14** [comment]
Because I am bad at Git mostly. I did this before my other branch was merged into master, and I was relying on that functionality. So I merged it into this branch yesterday. I figured because we are squashing and merging, that it wouldn't be a big deal though.

**Comment by BenHSmith13** [comment]
We should probably do some git-foo on this to get it down to just the code you wrote for the PR, that way we won't overwrite anything we may have changed in the last day with older code..

**Comment by nick-benoit14** [comment]
Doesn't the diff show everything that is different between current master, and this branch? I would say it might be worth the effort if this PR was bigger than 13 changes and included changes in files that weren't strictly audio upload centric. I am happy to look into figuring that out though if you think it is worth it after looking at the changes.

**Comment by BenHSmith13** [comment]
It's probably fine, I just worry we will inadvertently rollback some code.

**Comment by BenHSmith13** [comment]
# LGTM

**Pull request merged**
